container:
  image: cirrusci/android-sdk:30

build_task:
  # 1. ุชุซุจูุช ุฃุฏุงุฉ jq ููุฑุงุกุฉ ูููุงุช JSON
  install_jq_script: |
    sudo apt-get update
    sudo apt-get install -y jq

  # 2. ูุฑุงุกุฉ ุงูุฅุนุฏุงุฏุงุช ูู app_config.json ูุชุญููููุง ููุชุบูุฑุงุช ุจูุฆุฉ
  # ุซู ุจูุงุก ุงูุชุทุจูู ุจุงุณุชุฎุฏุงู ูุฐู ุงููุชุบูุฑุงุช
  build_script: |
    echo "reading app_config.json..."
    
    # ุงุณุชุฎุฑุงุฌ ุงูุจูุงูุงุช
    export APP_NAME=$(jq -r .APP_NAME app_config.json)
    export PACKAGE_NAME=$(jq -r .PACKAGE_NAME app_config.json)
    export APP_URL=$(jq -r .APP_URL app_config.json)
    export ICON_URL=$(jq -r .ICON_URL app_config.json)
    
    echo "๐ Building App: $APP_NAME ($PACKAGE_NAME)"
    echo "๐ URL: $APP_URL"
    
    # ููุง ูุชู ุชุดุบูู ุณูุฑูุจุช ุงูุจูุงุก ุงูุฎุงุต ุจู (ุชุฃูุฏ ูู ูุฌูุฏ build_apk.sh ุฃู ุนุฏู ุงูุณุทุฑ ุฃุฏูุงู)
    # ูุฐุง ูุซุงูุ ุนุฏูู ุญุณุจ ุทุฑููุฉ ุจูุงุฆู ุงูุญุงููุฉ
    # ./gradlew assembleDebug -PappName="$APP_NAME" -PpackageName="$PACKAGE_NAME"
    
    echo "โ๏ธ NOTE: Replace the line above with your actual build command"
    echo "Build simulated for config test."

  # 3. ุญูุธ ููู APK ุงููุงุชุฌ (Artifacts)
  apk_artifacts:
    path: "**/*.apk"
